icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[[block]]
block = "custom"
interval = 10
command = ''' mosquitto_sub -h 127.0.0.1 -t "tele/+/SENSOR" -C 1 | jq '.DHT11.Temperature' '''
format = "{$text}°C"

[icons]
icons = "material-nf"
[icons.overrides]
bat = ["", "", "", ""]
bat_charging = "󰢝"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = "$icon $percentage"

[[block]]
block = "net"
format = "$icon {$signal_strength}"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %d/%m %T') "
