#!/bin/sh

# Set keyboard repeat rate
xset r rate 300 50

# Set layout and switching with both Shift keys
setxkbmap -layout us,ru -option 'grp:shifts_toggle'

# Remap Caps Lock to Control
setxkbmap -option 'caps:ctrl_modifier'

# Use xcape to make Control (i.e., remapped Caps Lock) send Escape when tapped
killall xcape 2>/dev/null ; xcape -e 'Control_L=Escape'

# Make sure Caps Lock is off (even though we remapped it)
xset -q | grep -q "Caps Lock:\s*on" && xdotool key Caps_Lock
